version: '3.8'

services:
  selinux-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PORT=3000
      - BIND_ADDR=0.0.0.0
    volumes:
      # Mount SSH keys if needed
      - ~/.ssh:/root/.ssh:ro
    networks:
      - selinux-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a test SSH server for development
  test-ssh-server:
    image: linuxserver/openssh-server
    ports:
      - "2222:2222"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PUBLIC_KEY_FILE=/config/authorized_keys
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=true
      - USER_NAME=testuser
      - USER_PASSWORD=testpass
    volumes:
      - ./test-ssh-config:/config
    networks:
      - selinux-net
    profiles:
      - development

networks:
  selinux-net:
    driver: bridge